version: '3'
services:
    image-convertor:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - db
    db:
        image: postgres:14
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        restart: always
